#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    web-fun-phpmyadmin-80-http:
      entrypoints:
        - http-8036
      rule: HostRegexp(`^web-fun\.ddev\.site$`)
      
      service: "web-fun-phpmyadmin-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "web-fun-redirectHttps"
    web-fun-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^web-fun\.ddev\.site$`)
      
      service: "web-fun-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "web-fun-redirectHttps"
    web-fun-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^web-fun\.ddev\.site$`)
      
      service: "web-fun-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "web-fun-redirectHttps"
    
    
    web-fun-phpmyadmin-80-https:
      entrypoints:
        - http-8037
      rule: HostRegexp(`^web-fun\.ddev\.site$`)
      
      service: "web-fun-phpmyadmin-80"
      ruleSyntax: v3
      
      tls: true
      
    
    
    web-fun-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^web-fun\.ddev\.site$`)
      
      service: "web-fun-web-80"
      ruleSyntax: v3
      
      tls: true
      
    web-fun-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^web-fun\.ddev\.site$`)
      
      service: "web-fun-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    web-fun-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    web-fun-phpmyadmin-80:
      loadbalancer:
        servers:
          - url: http://ddev-web-fun-phpmyadmin:80
        
    
    web-fun-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-web-fun-web:80
        
    web-fun-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-web-fun-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/web-fun.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/web-fun.key